### ISSUE TITLE
How to use this in vuejs using import from node_modules?

### ISSUE THREAD

**Issue by tsulatsitamim** [gullerya/sign-pad#18]

**Comment by gullerya** [comment]
Hi, sorry for delay, I've been busy with something else.

I'll try to describe it in most general way and then we can dive into your project specifics:
- in your Vue component do import of the `sign-pad` just as you do import of anything else (see the readme example)
- in your Vue's component HTML template just put the element as in the examples: `<sign-pad></sign-pad>`

Start from this point.
What you should have at that point is, that the component initialized correctly and you can see the pad on the screen and draw on it.

If we are on the same page up till now, then now you can start customizing things, like bind and event for `change` (see Vue for that part, should be standard pattern), add handler and in the handler function do whatever you need with the signature (again, for this part there are examples).

Please notify me where it goes wrong for you, I'll collect all the way down to the resolution and will add a CodePen example accordingly.

**Comment by gullerya** [comment]
Here is a CodePen example of usage in Vue component - https://codepen.io/gullerya/pen/xxgPLRG
For convenience I'm using import from CDN flavor, but the `node_modules` based one is the same beside the path.

I've added this to the documentation as well (as of `1.3.1`).

**Comment by tsulatsitamim** [comment]
thank you for your detail explanation and providing the example. hope this library become popular.
